version: '3.7'
services:
  app:
    build:
      context: .
    image: api
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_MEMORY_LIMIT=1G
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: gestaocentral-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestaocentral
    volumes:
      - database-data:/var/lib/mysql
      - ./database/logs:/var/log/mysql
volumes:
  database-data:
